TeamLID.TravelExperts.App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TeamLID.TravelExperts.App.Models;

namespace TeamLID.TravelExperts.App.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TeamLID.TravelExperts.App/Controllers/PackagesController.cs
/*
Author: Ibraheem
Purpose: Retrieve and display all packages
*/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TeamLID.TravelExperts.App.Models;
using TeamLID.TravelExperts.App.Models.DataManager;
using TeamLID.TravelExperts.Repository.Domain;

namespace TeamLID.TravelExperts.App.Controllers
{
    public class PackagesController : Controller
    {
        private readonly TravelExpertsContext _context;

        public object PackagesManager { get; private set; }

        public PackagesController(TravelExpertsContext context)
        {
            _context = context;
        }

        // GET: Packages
        //async Task<>
        //await _context.Packages.ToListAsync()
        public ActionResult Index()
        {
            var packages = PackagesDataManager.GetAll()
                .Select(pck => new PackagesModel
                {
                    PackageId = pck.PackageId,
                    PkgName = pck.PkgName,
                    PkgStartDate = pck.PkgStartDate,
                    PkgEndDate = pck.PkgEndDate,
                    PkgDesc = pck.PkgDesc,
                    PkgBasePrice = Convert.ToString(Math.Round((decimal)(pck.PkgBasePrice + pck.PkgAgencyCommission), 0))
                }).ToList();

            return View(packages);

        }

        // GET: Packages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var packages = await _context.Packages
                .FirstOrDefaultAsync(m => m.PackageId == id);
            if (packages == null)
            {
                return NotFound();
            }

            return View(packages);
        }

        // GET: Packages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Packages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PackageId,PkgName,PkgStartDate,PkgEndDate,PkgDesc,PkgBasePrice,PkgAgencyCommission")] Packages packages)
        {
            if (ModelState.IsValid)
            {
                _context.Add(packages);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(packages);
        }

        // GET: Packages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var packages = await _context.Packages.FindAsync(id);
            if (packages == null)
            {
                return NotFound();
            }
            return View(packages);
        }

        // POST: Packages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PackageId,PkgName,PkgStartDate,PkgEndDate,PkgDesc,PkgBasePrice,PkgAgencyCommission")] Packages packages)
        {
            if (id != packages.PackageId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(packages);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PackagesExists(packages.PackageId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(packages);
        }

        // GET: Packages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var packages = await _context.Packages
                .FirstOrDefaultAsync(m => m.PackageId == id);
            if (packages == null)
            {
                return NotFound();
            }

            return View(packages);
        }

        // POST: Packages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var packages = await _context.Packages.FindAsync(id);
            _context.Packages.Remove(packages);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PackagesExists(int id)
        {
            return _context.Packages.Any(e => e.PackageId == id);
        }
    }
}

TeamLID.TravelExperts.App/Views/Home/Index.cshtml
@*/*
Author: Ibraheem
Purpose: Good design of landing page
*/*@

@{
    ViewData["Title"] = "Home Page";
}

<div class="container-fluid">
    <div class="bd-example">
        <div id="carouselExampleCaptions" class="carousel slide wow zoomIn" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="~/images/Travel3.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        @*<h5>First slide label</h5>
                            <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>*@
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="~/images/Travel1.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        @*<h5>Second slide label</h5>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>*@
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="~/images/Travel2.jpg" class="d-block w-100" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                        @*<h5>Third slide label</h5>
                            <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>*@
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<br />
<br />
<div class="container container-greetings">
    <h1 class="landing-greetings h1-responsive"> Welcome to travel experts</h1>

    <p class='lead text-center'>The world is at your fingertips... Explore!!</p>
</div>

<!-- Begin Main -->
<main>
    <div class="container">
        <div class="main">

            <h4 class="packages-display h4-responsive"> Package Deals</h4>

            <!-- <hr> -->
            <br>
            <div class="card-deck">
                <div class="card package wow slideInLeft" data-wow-delay="500ms">
                    <img src="~/images/carib-new.jpeg" class="card-img-top" alt="caribbean">
                    <div class="card-body">
                        <h4 class="card-title h4-responsive"> <strong> Caribbean New Year</strong></h4>
                        <p class="card-text">Cruise the caribbean and celebrate the New Year.</p>
                    </div>
                    <blockquote class="blockquote mb-0 card-body">
                        <footer class="">
                            <p class='lead'> CAD$ 5200 </p>
                        </footer>
                    </blockquote>
                </div>
                <div class="card package wow slideInUp" data-wow-delay="0.1s">
                    <img src="~/images/Polyn.jpeg" class="card-img-top" alt="polynesian">
                    <div class="card-body">
                        <h4 class="card-title h4-responsive"> <strong> Polynesian Paradise</strong></h4>
                        <p class="card-text">8 Days All Inclusive Hawaiian Vacation.</p>
                    </div>
                    <blockquote class="blockquote mb-0 card-body">
                        <footer class="">
                            <p class='lead'> CAD$ 3310 </p>
                        </footer>
                    </blockquote>
                </div>
                <div class="card package wow slideInRight" data-wow-delay="0.2s">
                    <img src="~/images/Asian.jpeg" class="card-img-top" alt="asian">
                    <div class="card-body">
                        <h4 class="card-title h4-responsive"> <strong>Asian Expedition </strong></h4>
                        <p class="card-text">Airfaire, Hotel and Eco Tour.</p>
                    </div>

                    <blockquote class="blockquote mb-0 card-body">
                        <footer class="">
                            <p class='lead'> CAD$ 3100 </p>
                        </footer>
                    </blockquote>
                </div>
            </div>
            <br>
            <div class="wow fadeInUp" data-wow-delay="250ms">
                <a asp-controller="Packages" asp-action="Index"><button class='btn btn-outline-primary btn-block float-center more'>More</button></a>
            </div>
        </div>
    </div>
</main>